# -*- coding: utf-8 -*-
"""volume_of_sphere

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vokwRuHaiTCCFxFaHGlx5kGWUzlB0L49
"""

def calculate_volume_of_sphere(radius):
  pi=3.14
  volume_of_sphere=(4/3)*pi*radius**3
  return volume_of_sphere

sphereS_radius=[30,40]
for radius in sphereS_radius:
  volume_of_sphere=calculate_volume_of_sphere(radius)
  print(volume_of_sphere)